import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "@/components/ClientLayout";
import { UserProvider } from "@/contexts/UserContext";
import { Toaster } from "react-hot-toast";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          <Toaster
            position="top-center"
            toastOptions={{
              duration: 3000,
              style: {
                background: "#fff",
                color: "#333",
                boxShadow: "0 3px 10px rgba(0,0,0,0.1)",
                borderRadius: "8px",
                padding: "12px 20px",
                maxWidth: "500px",
                width: "max-content",
                whiteSpace: "nowrap",
              },
              success: {
                style: {
                  border: "1px solid #10B981",
                },
                iconTheme: {
                  primary: "#10B981",
                  secondary: "#FFFBEB",
                },
              },
              error: {
                style: {
                  border: "1px solid #EF4444",
                },
                iconTheme: {
                  primary: "#EF4444",
                  secondary: "#FFFBEB",
                },
              },
            }}
          />
          <ClientLayout>{children}</ClientLayout>
        </UserProvider>
      </body>
    </html>
  );
}
