custom:
  site:
    name: "AniDoc"
    cookieDomain: "${custom.prod.cookieDomain}"
    frontUrl: "${custom.prod.frontUrl}"
    backUrl: "${custom.prod.backUrl}"

  cookieDomain: NEED_TO_INPUT

spring:
  datasource:
    url: jdbc:mysql://mysql_1:3306/anidocdb
    username: ll_local
    password: ${custom.prod.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
